[package]
name = "claude-native-binding"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.15", features = ["napi4"] }
napi-derive = "2.16.13"
